<?php
/**
 * Pratech_Banners
 *
 * PHP version 8.x
 *
 * @category  PHP
 * @package   Pratech\Banners
 * @author    Puneet Mittal <puneet.mittal@pratechbrands.com>
 * @copyright 2023 Copyright (c) Pratech Brands Private Limited
 * @link      https://pratechbrands.com/
 **/

use Pratech\Banners\Block\Adminhtml\Slider\AssignBanners; ?>

<?php
/** @var AssignBanners $block */
$blockGrid = $block->getBlockGrid();
$gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?= $block->getGridHtml() ?>
<input type="hidden"
       name="pratech_slider_banner"
       data-form-part="custom_slider_form"
       id="pratech_slider_banner"
       value=""/>
<script type="text/x-magento-init">
    {
        "*": {
            "Pratech_Banners/js/assign-banners": {
                "selectedBanners":  <?= /* @noEscape */ $block->getBannerJson() ?>,
                "gridJsObjectName": <?= /* @noEscape */ '"' . $gridJsObjectName . '"' ?: '{}' ?>
            }
        }
    }
</script>
<script>
    require('mage/apply/main').apply();
</script>
