<?php
/**
 * Pratech_VideoContent
 *
 * PHP version 8.x
 *
 * @category  PHP
 * @package   Pratech\VideoContent
 * @author    Akash Panwar <akash.panwar@pratechbrands.com>
 * @copyright 2025 Copyright (c) Pratech Brands Private Limited
 * @link      https://pratechbrands.com/
 **/

use Pratech\VideoContent\Block\Adminhtml\Slider\AssignVideos; ?>

<?php
/** @var AssignVideos $block */
$blockGrid = $block->getBlockGrid();
$gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?= $block->getGridHtml() ?>
<input type="hidden"
       name="video_slider_mapping"
       data-form-part="video_slider_form"
       id="video_slider_mapping"
       value=""/>
<script type="text/x-magento-init">
    {
        "*": {
            "Pratech_VideoContent/js/assign-videos": {
                "selectedVideos":  <?= /* @noEscape */ $block->getVideoJson() ?>,
                "gridJsObjectName": <?= /* @noEscape */ '"' . $gridJsObjectName . '"' ?: '{}' ?>
            }
        }
    }
</script>
<script>
    require('mage/apply/main').apply();
</script>
