<?php /** @var $block \Magento\Sales\Block\Adminhtml\Items\Renderer\DefaultRenderer */ ?>
<?php $_item = $block->getItem() ?>
<?php $block->setPriceDataObject($_item); ?>
<?php
$qtyOrdered = $_item->getQtyOrdered() ?? 0;
$qtyCanceled = $_item->getQtyCanceled() ?? 0;
$canCancelItem = $qtyOrdered - $qtyCanceled > 0 ? true : false;
?>
<tr>
    <td class="col-product"><?= $block->getColumnHtml($_item, 'name') ?></td>
    <td class="col-price">
        <?= $block->getColumnHtml($_item, 'price') ?>
    </td>
    <td class="col-ordered-qty"><?= $block->getColumnHtml($_item, 'qty') ?></td>
    <td class="col-refund col-qty">
    <?php if ($block->canEditQty()): ?>
        <input type="checkbox"
                class="admin__control-checkbox"
                name="partialcancel[items][<?= (int) $_item->getItemId() ?>][cancel]"
                value="1"<?php if (!$canCancelItem): ?> disabled<?php endif; ?>/>
        <label class="admin__field-label"></label>
    <?php else: ?>
        <?= (float) $_item->getQty() ?>
    <?php endif; ?>
    </td>
    <td class="col-subtotal">
        <?= $block->getColumnHtml($_item, 'subtotal') ?>
    </td>
    <td class="col-tax-amount"><?= /* @noEscape */ $block->displayPriceAttribute('tax_amount') ?></td>
    <td class="col-discont"><?= /* @noEscape */ $block->displayPriceAttribute('discount_amount') ?></td>
    <td class="col-total last">
        <?= $block->getColumnHtml($_item, 'total') ?>
    </td>
</tr>
