<?php
/** @var AssignRules $block */

use Pratech\Coupon\Block\Adminhtml\AssignRules;

$blockGrid = $block->getBlockGrid();
$gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?= $block->getGridHtml() ?>
<input type="hidden"
       name="stackable_rule_ids"
       data-form-part="sales_rule_form"
       id="stackable_rule_ids"
       value=""/>
<script type="text/x-magento-init">
    {
        "*": {
            "Pratech_Coupon/js/assign-rules": {
                "selectedRules": <?= /* @noEscape */$block->getRulesJson() ?>,
                "gridJsObjectName": <?= /* @noEscape */'"' . $gridJsObjectName . '"' ?: '{}' ?>
            }
        }
    }
</script>
<script>
    require('mage/apply/main').apply();
</script>
