<?php

use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Pratech\RedisIntegration\Block\Cache\Additional;
use Pratech\RedisIntegration\Block\Cache\Permissions;

/** @var SecureHtmlRenderer $secureRenderer */
/** @var Additional $block */
/** @var Permissions $permissions */
$permissions = $block->getData('permissions');

?>
<?php if ($permissions && $permissions->hasAccessToRedisActions()): ?>
    <div class="additional-cache-management">
        <h2>
            <span><?= $escaper->escapeHtml(__('Redis Cache Management')); ?></span>
        </h2>
        <?php if ($permissions->hasAccessToCatalogCachePostImport()): ?>
            <p>
                <button id="cleanPostImportCache" type="button">
                    <?= $escaper->escapeHtml(__('Post Import Cache Flush')); ?>
                </button>
                <?= /* @noEscape */
                $secureRenderer->renderEventListenerAsTag(
                    'onclick',
                    'setLocation(\'' . $escaper->escapeJs($block->getPostImportCacheUrl()) . '\')',
                    'button#cleanPostImportCache'
                ) ?>
                <span><?= $escaper->escapeHtml(__('Mandatory to flush the cache post import')); ?></span>
            </p>
        <?php endif; ?>
        <?php if ($permissions->hasAccessToFlushAttributeMapping()): ?>
            <p>
                <button id="cleanAttributeMappingCache" type="button">
                    <?= $escaper->escapeHtml(__('Flush Attribute Mapping')); ?>
                </button>
                <?= /* @noEscape */
                $secureRenderer->renderEventListenerAsTag(
                    'onclick',
                    'setLocation(\'' . $escaper->escapeJs($block->getCleanAttributeMappingCacheUrl()) . '\')',
                    'button#cleanAttributeMappingCache'
                ) ?>
                <span><?= $escaper->escapeHtml(__('Product Attribute Mapping to specific category')); ?></span>
            </p>
        <?php endif; ?>
        <?php if ($permissions->hasAccessToFlushReviews()): ?>
            <p>
                <button id="flushReviews" type="button">
                    <?= $escaper->escapeHtml(__('Flush Reviews')); ?>
                </button>
                <?= /* @noEscape */
                $secureRenderer->renderEventListenerAsTag(
                    'onclick',
                    'setLocation(\'' . $escaper->escapeJs($block->getCleanReviewsUrl()) . '\')',
                    'button#flushReviews'
                ) ?>
                <span>
                    <?= $escaper->escapeHtml(__('To be used when there is change in reviews from admin')); ?>
                </span>
            </p>
        <?php endif; ?>
        <?php if ($permissions->hasAccessToFlushCatalog()): ?>
            <p>
                <button id="flushCatalog" type="button">
                    <?= $escaper->escapeHtml(__('Flush Catalog')); ?>
                </button>
                <?= /* @noEscape */
                $secureRenderer->renderEventListenerAsTag(
                    'onclick',
                    'setLocation(\'' . $escaper->escapeJs($block->getCleanCatalogUrl()) . '\')',
                    'button#flushCatalog'
                ) ?>
                <span>
                    <?= $escaper->escapeHtml(
                        __('To be used when there is change in
                        Stores -> Configuration -> Pratech -> Product -> Attribute Suffix Configuration')
                    ); ?>
                </span>
            </p>
        <?php endif; ?>
        <?php if ($permissions->hasAccessToFlushSystemConfig()): ?>
            <p>
                <button id="flushSystemConfig" type="button">
                    <?= $escaper->escapeHtml(__('Flush System Config')); ?>
                </button>
                <?= /* @noEscape */
                $secureRenderer->renderEventListenerAsTag(
                    'onclick',
                    'setLocation(\'' . $escaper->escapeJs($block->getSystemConfigUrl()) . '\')',
                    'button#flushSystemConfig'
                ) ?>
                <span>
                    <?= $escaper->escapeHtml(
                        __('To be used when there is change in Stores -> System -> Configuration')
                    ); ?>
                </span>
            </p>
        <?php endif; ?>
        <?php if ($permissions->hasAccessToFlushCustomerWidget()): ?>
            <p>
                <button id="flushCustomerWidget" type="button">
                    <?= $escaper->escapeHtml(__('Flush Customer Widget')); ?>
                </button>
                <?= /* @noEscape */
                $secureRenderer->renderEventListenerAsTag(
                    'onclick',
                    'setLocation(\'' . $escaper->escapeJs($block->getCustomerWidgetUrl()) . '\')',
                    'button#flushCustomerWidget'
                ) ?>
                <span>
                    <?= $escaper->escapeHtml(
                        __('To be used when there is change in Customer Personalized Widget')
                    ); ?>
                </span>
            </p>
        <?php endif; ?>
        <?php if ($permissions->hasAccessToFlushQuizCache()): ?>
            <p>
                <button id="flushQuiz" type="button">
                    <?= $escaper->escapeHtml(__('Flush Quiz')); ?>
                </button>
                <?= /* @noEscape */
                $secureRenderer->renderEventListenerAsTag(
                    'onclick',
                    'setLocation(\'' . $escaper->escapeJs($block->getQuizUrl()) . '\')',
                    'button#flushQuiz'
                ) ?>
                <span>
                    <?= $escaper->escapeHtml(
                        __('To be used when there is change in Quiz')
                    ); ?>
                </span>
            </p>
        <?php endif; ?>

        <?php if ($permissions->hasAccessToFlushVideoCache()): ?>
            <p>
                <button id="flushVideos" type="button">
                    <?= $escaper->escapeHtml(__('Flush Videos')); ?>
                </button>
                <?= /* @noEscape */
                $secureRenderer->renderEventListenerAsTag(
                    'onclick',
                    'setLocation(\'' . $escaper->escapeJs($block->getVideoUrl()) . '\')',
                    'button#flushVideos'
                ) ?>
                <span>
                    <?= $escaper->escapeHtml(
                        __('To be used when there is change in Videos')
                    ); ?>
                </span>
            </p>
        <?php endif; ?>
    </div>
<?php endif; ?>

