<?php
/**
 * Pratech_VideoContent
 *
 * PHP version 8.x
 *
 * @category  PHP
 * @package   Pratech\VideoContent
 * @author    Akash Panwar <akash.panwar@pratechbrands.com>
 * @copyright 2025 Copyright (c) Pratech Brands Private Limited
 * @link      https://pratechbrands.com/
 **/

use Pratech\VideoContent\Block\Adminhtml\Video\AssignProducts;

/** @var AssignProducts $block */
$blockGrid = $block->getBlockGrid();
$gridJsObjectName = $blockGrid->getJsObjectName();
?>

<?= $block->getGridHtml() ?>

<input type="hidden"
       name="video_products"
       data-form-part="video_form"
       id="video_products"
       value=""
/>
<script type="text/x-magento-init">
    {
        "*": {
            "Pratech_VideoContent/js/assign-products": {
                "selectedProducts": <?= /* @noEscape */ $block->getProductsJson() ?>,
                "gridJsObjectName": <?= /* @noEscape */ '"' . $gridJsObjectName . '"' ?: '{}' ?>
            }
        }
    }
</script>
<script>
    require('mage/apply/main').apply();
</script>
