<?php

/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<?php $scriptString = <<<script
require([
    'jquery',
    "uiRegistry",
    'Magento_Ui/js/modal/alert',
    'prototype'
], function(jQuery, registry, alert) {

//<![CDATA[
function refreshPromoCodesGrid(grid, gridMassAction, transport) {
    grid.reload();
    gridMassAction.unselectAll();
}

function generatePromoCodes(idPrefix, generateUrl, grid) {
    $(idPrefix + 'information_fieldset').removeClassName('ignore-validate');
    var listInvalidElement = [];
    var validationResult = $(idPrefix + 'information_fieldset').select('input',
            'select', 'textarea').collect( function(elm) {
        var validateOneElementResult = jQuery.validator.validateSingleElement(elm);
        if (!validateOneElementResult) {
            listInvalidElement.push(elm);
        }
        return validateOneElementResult;
    }).all();
    if (listInvalidElement.length) {
        listInvalidElement[0].focus();
    }

    $(idPrefix + 'information_fieldset').addClassName('ignore-validate');

    if (!validationResult) {
        return;
    }
    var elements = $(idPrefix + 'information_fieldset').select('input', 'select', 'textarea');

    var params = Form.serializeElements(elements, true);
    params.form_key = FORM_KEY;
    if (\$$('#'+idPrefix + 'information_fieldset .messages')) {
        \$$('#'+idPrefix + 'information_fieldset .messages')[0].update();
    }
    if ($('messages')) {
        $('messages').update();
    }
    var promoCodesGrid = eval(grid);
    new Ajax.Request(generateUrl, {
        parameters :params,
        method :'post',
        onComplete : function (transport, param){
            var response = false;
            if (transport && transport.responseText) {
                try {
                    response = JSON.parse(transport.responseText);
                } catch (e) {
                    console.warn('An error occurred while parsing response');
                }
            }
            if (promoCodesGrid) {
                promoCodesGrid.reload();
            }
            if (response && response.messages) {
                if (\$$('#'+idPrefix + 'information_fieldset .messages')) {
                    \$$('#'+idPrefix + 'information_fieldset .messages')[0].update(response.messages);
                } else if ($('messages')) {
                    $('messages').update(response.messages);
                }
            }
            if (response && response.error) {
                alert({
                    content: response.error
                });
            }
        }
    });
}

function validatePromoCodeGenerate(elm) {
    jQuery.validator.validateSingleElement(elm);
}

window.validatePromoCodeGenerate = validatePromoCodeGenerate;
window.generatePromoCodes = generatePromoCodes;
window.refreshPromoCodesGrid = refreshPromoCodesGrid;
});
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
